version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: equadis
      MYSQL_PASSWORD: dummypassword
      MYSQL_DATABASE: banking-core

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=equadis
      - RABBITMQ_DEFAULT_PASS=dummypassword
    ports:
      - "5672:5672"
      - "15672:15672"

    #volumes If we want to persist data locally and not in container